name: Build IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      
      - name: Make script executable
        run: chmod +x ipabuild.sh
      
      - name: Build IPA
        run: ./ipabuild.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PancakeStore
          path: PancakeStore.ipa  # 改成脚本实际生成的文件名
